---
- name: Install Apache
  apt: pkg="apache2" state=present

- name: Configure Apache
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf

- name: Delete default web root
  file: path=/var/www/html state=absent
  when: apache_delete_default_site
