---
galaxy_info:
  author: Hector Castro
  description: An Ansible role for installing Git.
  company: eclecticLabs Inc.
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: RedHat
    versions:
    - 7.2
  categories:
  - development
dependencies: []
