production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: names
  pool: 5
  username: root
  password: password
  host: mysql

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: names
  pool: 5
  username: root
  password: password
  host: mysql

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: names
  pool: 5
  username: root
  password: password
  host: mysql

