---
- name: Set up the Nodesource RPM directory for Node.js > 0.10.
  set_fact:
    nodejs_rhel_rpm_dir: "pub_{{ nodejs_version }}"
  when: nodejs_version != '4.4.5'

- name: Set up the Nodesource RPM variable for Node.js == 0.10.
  set_fact:
    nodejs_rhel_rpm_dir: "pub"
  when: nodejs_version == '4.4.5'

- name: Add Nodesource repositories for Node.js.
  yum:
    name: "https://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present

- name: Ensure Node.js and npm are installed.
  yum: "name=nodejs state=present enablerepo='epel,nodesource'"
