---
galaxy_info:
  description: An Ansible role for installing Python
  company: eclecticLabs Inc.
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - development
dependencies: []
