---
galaxy_info:
  description: An Ansible role for installing Memcached.
  company: eclecticLabs Inc.
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
  - web
dependencies: []
