- group:
    name: "{{item.name}}"
    gid: "{{item.gid}}"
  with_items: "{{users_groups}}"

- user:
    name: "{{item.name}}"
    groups: "{{item.groups|join(', ') }}"
    uid: "{{item.uid}}"
  with_items: "{{users_users}}"

- authorized_key:
    user: "{{item.name}}"
    key: "{{item.key}}"
  with_items: "{{users_users}}"

- name: configure sudoers
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: "%{{item.name}} ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: yes
  with_items: "{{users_groups}}"
  when: item.sudo
