#
# install Oracle JDK 1.x on CentOS
#
# Adapted from: http://blog.trifork.com/2013/04/02/ansible-example-playbook-to-setup-jenkins-slave/
# See also: http://java.dzone.com/articles/installing-oracle-java6-ubuntu
#

- name: uninstall messy packages to avoid blocking conditions
  script: ../files/uninstall-messy-jdk-packages.sh

- name: delete messy .rpm files to avoid blocking conditions
  script: ../files/delete-messy-rpm-files.sh  {{ jdk_download_path }}


- name: get JDK tarball (as RPM file)
  command: "wget --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie'  -O {{ jdk_tarball_file }}.rpm  {{ jdk_tarball_url }}.rpm"
  args:
    creates: "{{ jdk_download_path }}/jdk-tarball-{{ jdk_version }}"
    chdir:   "{{ jdk_download_path }}"


- name: install JDK
  command: rpm --force -Uvh  {{ jdk_tarball_file }}.rpm
  args:
    creates: "{{ jdk_download_path }}/jdk-{{ jdk_version }}"
    chdir:   "{{ jdk_download_path }}"


- name: clean up - uninstall messy packages
  script: ../files/uninstall-messy-jdk-packages.sh

- name: clean up - delete messy .rpm files
  script: ../files/delete-messy-rpm-files.sh  {{ jdk_download_path }}
