---
# file: tasks/use-rpm.yml
# Configure Oracle JDK common settings.
#

- name: check if specific version of Oracle JDK is installed?
  script: ../files/check-rpm-installed.sh  "{{ jdk_version }}"
  register: jdk_info
  changed_when: false
  failed_when: jdk_info.rc > 0

- debug: msg="{{ jdk_info.stdout_lines[0] }}"

- include: install-jdk-rpm.yml
  when: jdk_info.stdout.find('false') != -1
