---
workspace: /root

# Whether this role should install Bundler.
ruby_install_bundler: true

# A list of Ruby gems to install.
ruby_install_gems: ['dashing', 'sinatra', 'nokogiri', 'httparty',
'simple-rss', 'rest-client', 'graphite', 'sinatra-cross_origin',
'bundler', 'whenever', 'domain_name', 'json']

# The user account under which Ruby gems will be installed.
ruby_install_gems_user: "{{ ansible_user }}"

# If set to TRUE, ruby will be installed from source, using the version set with
# the 'ruby_version' variable instead of using a package.
ruby_install_from_source: true
ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.5.tar.gz
ruby_version: 2.2.5

# Default should usually work, but this will be overridden on Ubuntu 14.04.
ruby_rubygems_package_name: rubygems
