- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ami_baking_key.key_file | dirname }}"
    mode: 0700
    owner: build
    state: directory

- name: Install ssh key
  copy:
    content: "{{ ami_baking_key.ssh_key }}"
    dest: "{{ ami_baking_key.key_file }}"
    mode: 0600
    owner: build
